create-release:
    runs-on: ubuntu-latest
    # Run after all jobs have completed (regardless of success/failure), only on schedule
    if: ${{ always() && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.scan_filter == 'all')) }}
    needs:
      [
        wellington-scan,
        letstalk-scan,
        archives-online-scan,
        tutuki-scan,
        transportprojects-scan,
        careers-scan,
      ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Display artifact structure
        run: find all-artifacts -type f | sort

      - name: Generate tag version
        id: tag_version
        run: |
          DATE=$(date +'%Y-%m-%d')
          echo "new_tag=v${DATE}" >> $GITHUB_OUTPUT
          echo "date=${DATE}" >> $GITHUB_OUTPUT

      - name: Prepare release files
        run: |
          # Create release directory
          mkdir -p release-files

          # Copy all HTML reports to release directory
          find all-artifacts -type f -name "*.html" -exec cp {} release-files/ \;
          
          # If no HTML files found, copy all files as a fallback
          if [ ! "$(ls -A release-files)" ]; then
            echo "No HTML files found, copying all artifacts"
            find all-artifacts -type f -exec cp {} release-files/ \;
          fi

          # List what we're about to release
          echo "Files to be released:"
          ls -la release-files/
          
          # Ensure we have files to release
          if [ ! "$(ls -A release-files)" ]; then
            echo "No files found to release. Creating a placeholder to prevent release failure."
            echo "No accessibility reports generated" > release-files/no-reports.txt
          fi

      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: "Monthly accessibility reports"
          body: |
            # Reports - ${{ steps.tag_version.outputs.date }}

            These reports include automated accessibility scan results for:
            - wellington.govt.nz
            - letstalk.wellington.govt.nz
            - Archives online
            - Tutuki services
            - Transport projects
            - careers.wellington.govt.nz
          artifacts: "release-files/*"
          artifactErrorsFailBuild: true
          allowUpdates: true